---
"Naive Bays"
---

```{r}
library(ggplot2)
library(e1071)
library(dplyr)
library(caret)
```


#import the data
```{r}

data<-read.csv("899-final.csv")
colnames(data)
```

```{r}

data2<-data[c(3,13,18,19,20,21,22)]
str(data2)
```

#clean
```{r}

data2<-data2[!grepl("Unknown", data2$Crash.Severity),]
data2<-data2[!grepl("Not Reported", data2$Crash.Severity),]

table(data2$Crash.Severity)
```


```{r}

fivenum(data2$PRCP)
fivenum(data2$SNOW)
fivenum(data2$TMAX)
fivenum(data2$TMIN)
```

#label the level
```{r}

data2$PRCP<-cut(data2$PRCP, breaks = c(-Inf,0,0.098,0.39,2.0,4.96),
                   labels = c("NoRain", "0.01~0.098", "0.099~0.39","0.40~2.0","2.1~4.96"))

data2$SNOW<-cut(data2$SNOW, breaks = c(-Inf, 0.00,5.1,10,21),
                labels = c("NoSnow","0.01~5.1","5.2~9.99","10~21"))

data2$TMAX<-cut(data2$TMAX, breaks = c(-Inf, 32, 68, 103),
                labels = c("max<=32", "33~68", "69~103"))

data2$TMIN<-cut(data2$TMIN, breaks = c(-Inf, 32, 50, 77),
                labels = c("min<=32", "33~50", "51~77"))


table(data2$PRCP)
table(data2$SNOW)
table(data2$TMAX)
table(data2$TMIN)
```
```{r}

columns<-names(data2)
data2[,columns]<-lapply(data2[,columns], factor)
str(data2)
```


```{r}
ggplot(data2, aes(x=Ice, fill=Crash.Severity))+geom_bar(position = 'fill')
```
```{r}

ggplot(data2, aes(x=Weather.Condition, fill=Crash.Severity))+geom_bar(position = 'fill')
```



#Naive Bays Model
```{r}
naive_crash<-naiveBayes(Crash.Severity~., data=data2)
naive_crash
```


```{r}

set.seed(1000)
crash_test <- slice_sample(data2, prop=1)

train.df <- slice_head(crash_test, prop=0.6)
valid.df <- slice_tail(crash_test, prop=0.4)

```

```{r}

pre.crash1<-predict(naive_crash, newdata=train.df )
confusionMatrix(pre.crash1, train.df$Crash.Severity)
```

```{r}

pre.crash2<-predict(naive_crash, newdata=valid.df )
confusionMatrix(pre.crash2, valid.df$Crash.Severity)
```



# Weather condition, "Clear","Cloudy","Cloudy&Rain","Fog",Rain","Snow"
# PRCP, "NoRain", "0.01~0.098", "0.099~0.39","0.40~2.0","2.1~4.96"
# SNOW, "NoSnow","0.01~5.1","5.2~9.99","10~21"
# TMAX, "max<=32", "33~68", "69~103"
# TMIN, "min<=32", "33~50", "51~77"
```{r}

sample<-data.frame(Weather.Condition="Fog",PRCP="0.01~0.098", SNOW="0.01~5.1", TMAX="max<=32", TMIN="min<=32")

pre.sample<-predict(naive_crash, sample)
predict(naive_crash,newdata = sample, type = "raw")
```



